// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.facebook.i;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public final class a
{

    static Map a()
    {
        HashMap hashmap = new HashMap(286);
        ArrayList arraylist = new ArrayList(25);
        arraylist.add("US");
        arraylist.add("AG");
        arraylist.add("AI");
        arraylist.add("AS");
        arraylist.add("BB");
        arraylist.add("BM");
        arraylist.add("BS");
        arraylist.add("CA");
        arraylist.add("DM");
        arraylist.add("DO");
        arraylist.add("GD");
        arraylist.add("GU");
        arraylist.add("JM");
        arraylist.add("KN");
        arraylist.add("KY");
        arraylist.add("LC");
        arraylist.add("MP");
        arraylist.add("MS");
        arraylist.add("PR");
        arraylist.add("SX");
        arraylist.add("TC");
        arraylist.add("TT");
        arraylist.add("VC");
        arraylist.add("VG");
        arraylist.add("VI");
        hashmap.put(Integer.valueOf(1), arraylist);
        ArrayList arraylist1 = new ArrayList(2);
        arraylist1.add("RU");
        arraylist1.add("KZ");
        hashmap.put(Integer.valueOf(7), arraylist1);
        ArrayList arraylist2 = new ArrayList(1);
        arraylist2.add("EG");
        hashmap.put(Integer.valueOf(20), arraylist2);
        ArrayList arraylist3 = new ArrayList(1);
        arraylist3.add("ZA");
        hashmap.put(Integer.valueOf(27), arraylist3);
        ArrayList arraylist4 = new ArrayList(1);
        arraylist4.add("GR");
        hashmap.put(Integer.valueOf(30), arraylist4);
        ArrayList arraylist5 = new ArrayList(1);
        arraylist5.add("NL");
        hashmap.put(Integer.valueOf(31), arraylist5);
        ArrayList arraylist6 = new ArrayList(1);
        arraylist6.add("BE");
        hashmap.put(Integer.valueOf(32), arraylist6);
        ArrayList arraylist7 = new ArrayList(1);
        arraylist7.add("FR");
        hashmap.put(Integer.valueOf(33), arraylist7);
        ArrayList arraylist8 = new ArrayList(1);
        arraylist8.add("ES");
        hashmap.put(Integer.valueOf(34), arraylist8);
        ArrayList arraylist9 = new ArrayList(1);
        arraylist9.add("HU");
        hashmap.put(Integer.valueOf(36), arraylist9);
        ArrayList arraylist10 = new ArrayList(1);
        arraylist10.add("IT");
        hashmap.put(Integer.valueOf(39), arraylist10);
        ArrayList arraylist11 = new ArrayList(1);
        arraylist11.add("RO");
        hashmap.put(Integer.valueOf(40), arraylist11);
        ArrayList arraylist12 = new ArrayList(1);
        arraylist12.add("CH");
        hashmap.put(Integer.valueOf(41), arraylist12);
        ArrayList arraylist13 = new ArrayList(1);
        arraylist13.add("AT");
        hashmap.put(Integer.valueOf(43), arraylist13);
        ArrayList arraylist14 = new ArrayList(4);
        arraylist14.add("GB");
        arraylist14.add("GG");
        arraylist14.add("IM");
        arraylist14.add("JE");
        hashmap.put(Integer.valueOf(44), arraylist14);
        ArrayList arraylist15 = new ArrayList(1);
        arraylist15.add("DK");
        hashmap.put(Integer.valueOf(45), arraylist15);
        ArrayList arraylist16 = new ArrayList(1);
        arraylist16.add("SE");
        hashmap.put(Integer.valueOf(46), arraylist16);
        ArrayList arraylist17 = new ArrayList(2);
        arraylist17.add("NO");
        arraylist17.add("SJ");
        hashmap.put(Integer.valueOf(47), arraylist17);
        ArrayList arraylist18 = new ArrayList(1);
        arraylist18.add("PL");
        hashmap.put(Integer.valueOf(48), arraylist18);
        ArrayList arraylist19 = new ArrayList(1);
        arraylist19.add("DE");
        hashmap.put(Integer.valueOf(49), arraylist19);
        ArrayList arraylist20 = new ArrayList(1);
        arraylist20.add("PE");
        hashmap.put(Integer.valueOf(51), arraylist20);
        ArrayList arraylist21 = new ArrayList(1);
        arraylist21.add("MX");
        hashmap.put(Integer.valueOf(52), arraylist21);
        ArrayList arraylist22 = new ArrayList(1);
        arraylist22.add("CU");
        hashmap.put(Integer.valueOf(53), arraylist22);
        ArrayList arraylist23 = new ArrayList(1);
        arraylist23.add("AR");
        hashmap.put(Integer.valueOf(54), arraylist23);
        ArrayList arraylist24 = new ArrayList(1);
        arraylist24.add("BR");
        hashmap.put(Integer.valueOf(55), arraylist24);
        ArrayList arraylist25 = new ArrayList(1);
        arraylist25.add("CL");
        hashmap.put(Integer.valueOf(56), arraylist25);
        ArrayList arraylist26 = new ArrayList(1);
        arraylist26.add("CO");
        hashmap.put(Integer.valueOf(57), arraylist26);
        ArrayList arraylist27 = new ArrayList(1);
        arraylist27.add("VE");
        hashmap.put(Integer.valueOf(58), arraylist27);
        ArrayList arraylist28 = new ArrayList(1);
        arraylist28.add("MY");
        hashmap.put(Integer.valueOf(60), arraylist28);
        ArrayList arraylist29 = new ArrayList(3);
        arraylist29.add("AU");
        arraylist29.add("CC");
        arraylist29.add("CX");
        hashmap.put(Integer.valueOf(61), arraylist29);
        ArrayList arraylist30 = new ArrayList(1);
        arraylist30.add("ID");
        hashmap.put(Integer.valueOf(62), arraylist30);
        ArrayList arraylist31 = new ArrayList(1);
        arraylist31.add("PH");
        hashmap.put(Integer.valueOf(63), arraylist31);
        ArrayList arraylist32 = new ArrayList(1);
        arraylist32.add("NZ");
        hashmap.put(Integer.valueOf(64), arraylist32);
        ArrayList arraylist33 = new ArrayList(1);
        arraylist33.add("SG");
        hashmap.put(Integer.valueOf(65), arraylist33);
        ArrayList arraylist34 = new ArrayList(1);
        arraylist34.add("TH");
        hashmap.put(Integer.valueOf(66), arraylist34);
        ArrayList arraylist35 = new ArrayList(1);
        arraylist35.add("JP");
        hashmap.put(Integer.valueOf(81), arraylist35);
        ArrayList arraylist36 = new ArrayList(1);
        arraylist36.add("KR");
        hashmap.put(Integer.valueOf(82), arraylist36);
        ArrayList arraylist37 = new ArrayList(1);
        arraylist37.add("VN");
        hashmap.put(Integer.valueOf(84), arraylist37);
        ArrayList arraylist38 = new ArrayList(1);
        arraylist38.add("CN");
        hashmap.put(Integer.valueOf(86), arraylist38);
        ArrayList arraylist39 = new ArrayList(1);
        arraylist39.add("TR");
        hashmap.put(Integer.valueOf(90), arraylist39);
        ArrayList arraylist40 = new ArrayList(1);
        arraylist40.add("IN");
        hashmap.put(Integer.valueOf(91), arraylist40);
        ArrayList arraylist41 = new ArrayList(1);
        arraylist41.add("PK");
        hashmap.put(Integer.valueOf(92), arraylist41);
        ArrayList arraylist42 = new ArrayList(1);
        arraylist42.add("AF");
        hashmap.put(Integer.valueOf(93), arraylist42);
        ArrayList arraylist43 = new ArrayList(1);
        arraylist43.add("LK");
        hashmap.put(Integer.valueOf(94), arraylist43);
        ArrayList arraylist44 = new ArrayList(1);
        arraylist44.add("MM");
        hashmap.put(Integer.valueOf(95), arraylist44);
        ArrayList arraylist45 = new ArrayList(1);
        arraylist45.add("IR");
        hashmap.put(Integer.valueOf(98), arraylist45);
        ArrayList arraylist46 = new ArrayList(1);
        arraylist46.add("SS");
        hashmap.put(Integer.valueOf(211), arraylist46);
        ArrayList arraylist47 = new ArrayList(2);
        arraylist47.add("MA");
        arraylist47.add("EH");
        hashmap.put(Integer.valueOf(212), arraylist47);
        ArrayList arraylist48 = new ArrayList(1);
        arraylist48.add("DZ");
        hashmap.put(Integer.valueOf(213), arraylist48);
        ArrayList arraylist49 = new ArrayList(1);
        arraylist49.add("TN");
        hashmap.put(Integer.valueOf(216), arraylist49);
        ArrayList arraylist50 = new ArrayList(1);
        arraylist50.add("LY");
        hashmap.put(Integer.valueOf(218), arraylist50);
        ArrayList arraylist51 = new ArrayList(1);
        arraylist51.add("GM");
        hashmap.put(Integer.valueOf(220), arraylist51);
        ArrayList arraylist52 = new ArrayList(1);
        arraylist52.add("SN");
        hashmap.put(Integer.valueOf(221), arraylist52);
        ArrayList arraylist53 = new ArrayList(1);
        arraylist53.add("MR");
        hashmap.put(Integer.valueOf(222), arraylist53);
        ArrayList arraylist54 = new ArrayList(1);
        arraylist54.add("ML");
        hashmap.put(Integer.valueOf(223), arraylist54);
        ArrayList arraylist55 = new ArrayList(1);
        arraylist55.add("GN");
        hashmap.put(Integer.valueOf(224), arraylist55);
        ArrayList arraylist56 = new ArrayList(1);
        arraylist56.add("CI");
        hashmap.put(Integer.valueOf(225), arraylist56);
        ArrayList arraylist57 = new ArrayList(1);
        arraylist57.add("BF");
        hashmap.put(Integer.valueOf(226), arraylist57);
        ArrayList arraylist58 = new ArrayList(1);
        arraylist58.add("NE");
        hashmap.put(Integer.valueOf(227), arraylist58);
        ArrayList arraylist59 = new ArrayList(1);
        arraylist59.add("TG");
        hashmap.put(Integer.valueOf(228), arraylist59);
        ArrayList arraylist60 = new ArrayList(1);
        arraylist60.add("BJ");
        hashmap.put(Integer.valueOf(229), arraylist60);
        ArrayList arraylist61 = new ArrayList(1);
        arraylist61.add("MU");
        hashmap.put(Integer.valueOf(230), arraylist61);
        ArrayList arraylist62 = new ArrayList(1);
        arraylist62.add("LR");
        hashmap.put(Integer.valueOf(231), arraylist62);
        ArrayList arraylist63 = new ArrayList(1);
        arraylist63.add("SL");
        hashmap.put(Integer.valueOf(232), arraylist63);
        ArrayList arraylist64 = new ArrayList(1);
        arraylist64.add("GH");
        hashmap.put(Integer.valueOf(233), arraylist64);
        ArrayList arraylist65 = new ArrayList(1);
        arraylist65.add("NG");
        hashmap.put(Integer.valueOf(234), arraylist65);
        ArrayList arraylist66 = new ArrayList(1);
        arraylist66.add("TD");
        hashmap.put(Integer.valueOf(235), arraylist66);
        ArrayList arraylist67 = new ArrayList(1);
        arraylist67.add("CF");
        hashmap.put(Integer.valueOf(236), arraylist67);
        ArrayList arraylist68 = new ArrayList(1);
        arraylist68.add("CM");
        hashmap.put(Integer.valueOf(237), arraylist68);
        ArrayList arraylist69 = new ArrayList(1);
        arraylist69.add("CV");
        hashmap.put(Integer.valueOf(238), arraylist69);
        ArrayList arraylist70 = new ArrayList(1);
        arraylist70.add("ST");
        hashmap.put(Integer.valueOf(239), arraylist70);
        ArrayList arraylist71 = new ArrayList(1);
        arraylist71.add("GQ");
        hashmap.put(Integer.valueOf(240), arraylist71);
        ArrayList arraylist72 = new ArrayList(1);
        arraylist72.add("GA");
        hashmap.put(Integer.valueOf(241), arraylist72);
        ArrayList arraylist73 = new ArrayList(1);
        arraylist73.add("CG");
        hashmap.put(Integer.valueOf(242), arraylist73);
        ArrayList arraylist74 = new ArrayList(1);
        arraylist74.add("CD");
        hashmap.put(Integer.valueOf(243), arraylist74);
        ArrayList arraylist75 = new ArrayList(1);
        arraylist75.add("AO");
        hashmap.put(Integer.valueOf(244), arraylist75);
        ArrayList arraylist76 = new ArrayList(1);
        arraylist76.add("GW");
        hashmap.put(Integer.valueOf(245), arraylist76);
        ArrayList arraylist77 = new ArrayList(1);
        arraylist77.add("IO");
        hashmap.put(Integer.valueOf(246), arraylist77);
        ArrayList arraylist78 = new ArrayList(1);
        arraylist78.add("AC");
        hashmap.put(Integer.valueOf(247), arraylist78);
        ArrayList arraylist79 = new ArrayList(1);
        arraylist79.add("SC");
        hashmap.put(Integer.valueOf(248), arraylist79);
        ArrayList arraylist80 = new ArrayList(1);
        arraylist80.add("SD");
        hashmap.put(Integer.valueOf(249), arraylist80);
        ArrayList arraylist81 = new ArrayList(1);
        arraylist81.add("RW");
        hashmap.put(Integer.valueOf(250), arraylist81);
        ArrayList arraylist82 = new ArrayList(1);
        arraylist82.add("ET");
        hashmap.put(Integer.valueOf(251), arraylist82);
        ArrayList arraylist83 = new ArrayList(1);
        arraylist83.add("SO");
        hashmap.put(Integer.valueOf(252), arraylist83);
        ArrayList arraylist84 = new ArrayList(1);
        arraylist84.add("DJ");
        hashmap.put(Integer.valueOf(253), arraylist84);
        ArrayList arraylist85 = new ArrayList(1);
        arraylist85.add("KE");
        hashmap.put(Integer.valueOf(254), arraylist85);
        ArrayList arraylist86 = new ArrayList(1);
        arraylist86.add("TZ");
        hashmap.put(Integer.valueOf(255), arraylist86);
        ArrayList arraylist87 = new ArrayList(1);
        arraylist87.add("UG");
        hashmap.put(Integer.valueOf(256), arraylist87);
        ArrayList arraylist88 = new ArrayList(1);
        arraylist88.add("BI");
        hashmap.put(Integer.valueOf(257), arraylist88);
        ArrayList arraylist89 = new ArrayList(1);
        arraylist89.add("MZ");
        hashmap.put(Integer.valueOf(258), arraylist89);
        ArrayList arraylist90 = new ArrayList(1);
        arraylist90.add("ZM");
        hashmap.put(Integer.valueOf(260), arraylist90);
        ArrayList arraylist91 = new ArrayList(1);
        arraylist91.add("MG");
        hashmap.put(Integer.valueOf(261), arraylist91);
        ArrayList arraylist92 = new ArrayList(2);
        arraylist92.add("RE");
        arraylist92.add("YT");
        hashmap.put(Integer.valueOf(262), arraylist92);
        ArrayList arraylist93 = new ArrayList(1);
        arraylist93.add("ZW");
        hashmap.put(Integer.valueOf(263), arraylist93);
        ArrayList arraylist94 = new ArrayList(1);
        arraylist94.add("NA");
        hashmap.put(Integer.valueOf(264), arraylist94);
        ArrayList arraylist95 = new ArrayList(1);
        arraylist95.add("MW");
        hashmap.put(Integer.valueOf(265), arraylist95);
        ArrayList arraylist96 = new ArrayList(1);
        arraylist96.add("LS");
        hashmap.put(Integer.valueOf(266), arraylist96);
        ArrayList arraylist97 = new ArrayList(1);
        arraylist97.add("BW");
        hashmap.put(Integer.valueOf(267), arraylist97);
        ArrayList arraylist98 = new ArrayList(1);
        arraylist98.add("SZ");
        hashmap.put(Integer.valueOf(268), arraylist98);
        ArrayList arraylist99 = new ArrayList(1);
        arraylist99.add("KM");
        hashmap.put(Integer.valueOf(269), arraylist99);
        ArrayList arraylist100 = new ArrayList(2);
        arraylist100.add("SH");
        arraylist100.add("TA");
        hashmap.put(Integer.valueOf(290), arraylist100);
        ArrayList arraylist101 = new ArrayList(1);
        arraylist101.add("ER");
        hashmap.put(Integer.valueOf(291), arraylist101);
        ArrayList arraylist102 = new ArrayList(1);
        arraylist102.add("AW");
        hashmap.put(Integer.valueOf(297), arraylist102);
        ArrayList arraylist103 = new ArrayList(1);
        arraylist103.add("FO");
        hashmap.put(Integer.valueOf(298), arraylist103);
        ArrayList arraylist104 = new ArrayList(1);
        arraylist104.add("GL");
        hashmap.put(Integer.valueOf(299), arraylist104);
        ArrayList arraylist105 = new ArrayList(1);
        arraylist105.add("GI");
        hashmap.put(Integer.valueOf(350), arraylist105);
        ArrayList arraylist106 = new ArrayList(1);
        arraylist106.add("PT");
        hashmap.put(Integer.valueOf(351), arraylist106);
        ArrayList arraylist107 = new ArrayList(1);
        arraylist107.add("LU");
        hashmap.put(Integer.valueOf(352), arraylist107);
        ArrayList arraylist108 = new ArrayList(1);
        arraylist108.add("IE");
        hashmap.put(Integer.valueOf(353), arraylist108);
        ArrayList arraylist109 = new ArrayList(1);
        arraylist109.add("IS");
        hashmap.put(Integer.valueOf(354), arraylist109);
        ArrayList arraylist110 = new ArrayList(1);
        arraylist110.add("AL");
        hashmap.put(Integer.valueOf(355), arraylist110);
        ArrayList arraylist111 = new ArrayList(1);
        arraylist111.add("MT");
        hashmap.put(Integer.valueOf(356), arraylist111);
        ArrayList arraylist112 = new ArrayList(1);
        arraylist112.add("CY");
        hashmap.put(Integer.valueOf(357), arraylist112);
        ArrayList arraylist113 = new ArrayList(2);
        arraylist113.add("FI");
        arraylist113.add("AX");
        hashmap.put(Integer.valueOf(358), arraylist113);
        ArrayList arraylist114 = new ArrayList(1);
        arraylist114.add("BG");
        hashmap.put(Integer.valueOf(359), arraylist114);
        ArrayList arraylist115 = new ArrayList(1);
        arraylist115.add("LT");
        hashmap.put(Integer.valueOf(370), arraylist115);
        ArrayList arraylist116 = new ArrayList(1);
        arraylist116.add("LV");
        hashmap.put(Integer.valueOf(371), arraylist116);
        ArrayList arraylist117 = new ArrayList(1);
        arraylist117.add("EE");
        hashmap.put(Integer.valueOf(372), arraylist117);
        ArrayList arraylist118 = new ArrayList(1);
        arraylist118.add("MD");
        hashmap.put(Integer.valueOf(373), arraylist118);
        ArrayList arraylist119 = new ArrayList(1);
        arraylist119.add("AM");
        hashmap.put(Integer.valueOf(374), arraylist119);
        ArrayList arraylist120 = new ArrayList(1);
        arraylist120.add("BY");
        hashmap.put(Integer.valueOf(375), arraylist120);
        ArrayList arraylist121 = new ArrayList(1);
        arraylist121.add("AD");
        hashmap.put(Integer.valueOf(376), arraylist121);
        ArrayList arraylist122 = new ArrayList(1);
        arraylist122.add("MC");
        hashmap.put(Integer.valueOf(377), arraylist122);
        ArrayList arraylist123 = new ArrayList(1);
        arraylist123.add("SM");
        hashmap.put(Integer.valueOf(378), arraylist123);
        ArrayList arraylist124 = new ArrayList(1);
        arraylist124.add("VA");
        hashmap.put(Integer.valueOf(379), arraylist124);
        ArrayList arraylist125 = new ArrayList(1);
        arraylist125.add("UA");
        hashmap.put(Integer.valueOf(380), arraylist125);
        ArrayList arraylist126 = new ArrayList(1);
        arraylist126.add("RS");
        hashmap.put(Integer.valueOf(381), arraylist126);
        ArrayList arraylist127 = new ArrayList(1);
        arraylist127.add("ME");
        hashmap.put(Integer.valueOf(382), arraylist127);
        ArrayList arraylist128 = new ArrayList(1);
        arraylist128.add("HR");
        hashmap.put(Integer.valueOf(385), arraylist128);
        ArrayList arraylist129 = new ArrayList(1);
        arraylist129.add("SI");
        hashmap.put(Integer.valueOf(386), arraylist129);
        ArrayList arraylist130 = new ArrayList(1);
        arraylist130.add("BA");
        hashmap.put(Integer.valueOf(387), arraylist130);
        ArrayList arraylist131 = new ArrayList(1);
        arraylist131.add("MK");
        hashmap.put(Integer.valueOf(389), arraylist131);
        ArrayList arraylist132 = new ArrayList(1);
        arraylist132.add("CZ");
        hashmap.put(Integer.valueOf(420), arraylist132);
        ArrayList arraylist133 = new ArrayList(1);
        arraylist133.add("SK");
        hashmap.put(Integer.valueOf(421), arraylist133);
        ArrayList arraylist134 = new ArrayList(1);
        arraylist134.add("LI");
        hashmap.put(Integer.valueOf(423), arraylist134);
        ArrayList arraylist135 = new ArrayList(1);
        arraylist135.add("FK");
        hashmap.put(Integer.valueOf(500), arraylist135);
        ArrayList arraylist136 = new ArrayList(1);
        arraylist136.add("BZ");
        hashmap.put(Integer.valueOf(501), arraylist136);
        ArrayList arraylist137 = new ArrayList(1);
        arraylist137.add("GT");
        hashmap.put(Integer.valueOf(502), arraylist137);
        ArrayList arraylist138 = new ArrayList(1);
        arraylist138.add("SV");
        hashmap.put(Integer.valueOf(503), arraylist138);
        ArrayList arraylist139 = new ArrayList(1);
        arraylist139.add("HN");
        hashmap.put(Integer.valueOf(504), arraylist139);
        ArrayList arraylist140 = new ArrayList(1);
        arraylist140.add("NI");
        hashmap.put(Integer.valueOf(505), arraylist140);
        ArrayList arraylist141 = new ArrayList(1);
        arraylist141.add("CR");
        hashmap.put(Integer.valueOf(506), arraylist141);
        ArrayList arraylist142 = new ArrayList(1);
        arraylist142.add("PA");
        hashmap.put(Integer.valueOf(507), arraylist142);
        ArrayList arraylist143 = new ArrayList(1);
        arraylist143.add("PM");
        hashmap.put(Integer.valueOf(508), arraylist143);
        ArrayList arraylist144 = new ArrayList(1);
        arraylist144.add("HT");
        hashmap.put(Integer.valueOf(509), arraylist144);
        ArrayList arraylist145 = new ArrayList(3);
        arraylist145.add("GP");
        arraylist145.add("BL");
        arraylist145.add("MF");
        hashmap.put(Integer.valueOf(590), arraylist145);
        ArrayList arraylist146 = new ArrayList(1);
        arraylist146.add("BO");
        hashmap.put(Integer.valueOf(591), arraylist146);
        ArrayList arraylist147 = new ArrayList(1);
        arraylist147.add("GY");
        hashmap.put(Integer.valueOf(592), arraylist147);
        ArrayList arraylist148 = new ArrayList(1);
        arraylist148.add("EC");
        hashmap.put(Integer.valueOf(593), arraylist148);
        ArrayList arraylist149 = new ArrayList(1);
        arraylist149.add("GF");
        hashmap.put(Integer.valueOf(594), arraylist149);
        ArrayList arraylist150 = new ArrayList(1);
        arraylist150.add("PY");
        hashmap.put(Integer.valueOf(595), arraylist150);
        ArrayList arraylist151 = new ArrayList(1);
        arraylist151.add("MQ");
        hashmap.put(Integer.valueOf(596), arraylist151);
        ArrayList arraylist152 = new ArrayList(1);
        arraylist152.add("SR");
        hashmap.put(Integer.valueOf(597), arraylist152);
        ArrayList arraylist153 = new ArrayList(1);
        arraylist153.add("UY");
        hashmap.put(Integer.valueOf(598), arraylist153);
        ArrayList arraylist154 = new ArrayList(2);
        arraylist154.add("CW");
        arraylist154.add("BQ");
        hashmap.put(Integer.valueOf(599), arraylist154);
        ArrayList arraylist155 = new ArrayList(1);
        arraylist155.add("TL");
        hashmap.put(Integer.valueOf(670), arraylist155);
        ArrayList arraylist156 = new ArrayList(1);
        arraylist156.add("NF");
        hashmap.put(Integer.valueOf(672), arraylist156);
        ArrayList arraylist157 = new ArrayList(1);
        arraylist157.add("BN");
        hashmap.put(Integer.valueOf(673), arraylist157);
        ArrayList arraylist158 = new ArrayList(1);
        arraylist158.add("NR");
        hashmap.put(Integer.valueOf(674), arraylist158);
        ArrayList arraylist159 = new ArrayList(1);
        arraylist159.add("PG");
        hashmap.put(Integer.valueOf(675), arraylist159);
        ArrayList arraylist160 = new ArrayList(1);
        arraylist160.add("TO");
        hashmap.put(Integer.valueOf(676), arraylist160);
        ArrayList arraylist161 = new ArrayList(1);
        arraylist161.add("SB");
        hashmap.put(Integer.valueOf(677), arraylist161);
        ArrayList arraylist162 = new ArrayList(1);
        arraylist162.add("VU");
        hashmap.put(Integer.valueOf(678), arraylist162);
        ArrayList arraylist163 = new ArrayList(1);
        arraylist163.add("FJ");
        hashmap.put(Integer.valueOf(679), arraylist163);
        ArrayList arraylist164 = new ArrayList(1);
        arraylist164.add("PW");
        hashmap.put(Integer.valueOf(680), arraylist164);
        ArrayList arraylist165 = new ArrayList(1);
        arraylist165.add("WF");
        hashmap.put(Integer.valueOf(681), arraylist165);
        ArrayList arraylist166 = new ArrayList(1);
        arraylist166.add("CK");
        hashmap.put(Integer.valueOf(682), arraylist166);
        ArrayList arraylist167 = new ArrayList(1);
        arraylist167.add("NU");
        hashmap.put(Integer.valueOf(683), arraylist167);
        ArrayList arraylist168 = new ArrayList(1);
        arraylist168.add("WS");
        hashmap.put(Integer.valueOf(685), arraylist168);
        ArrayList arraylist169 = new ArrayList(1);
        arraylist169.add("KI");
        hashmap.put(Integer.valueOf(686), arraylist169);
        ArrayList arraylist170 = new ArrayList(1);
        arraylist170.add("NC");
        hashmap.put(Integer.valueOf(687), arraylist170);
        ArrayList arraylist171 = new ArrayList(1);
        arraylist171.add("TV");
        hashmap.put(Integer.valueOf(688), arraylist171);
        ArrayList arraylist172 = new ArrayList(1);
        arraylist172.add("PF");
        hashmap.put(Integer.valueOf(689), arraylist172);
        ArrayList arraylist173 = new ArrayList(1);
        arraylist173.add("TK");
        hashmap.put(Integer.valueOf(690), arraylist173);
        ArrayList arraylist174 = new ArrayList(1);
        arraylist174.add("FM");
        hashmap.put(Integer.valueOf(691), arraylist174);
        ArrayList arraylist175 = new ArrayList(1);
        arraylist175.add("MH");
        hashmap.put(Integer.valueOf(692), arraylist175);
        ArrayList arraylist176 = new ArrayList(1);
        arraylist176.add("001");
        hashmap.put(Integer.valueOf(800), arraylist176);
        ArrayList arraylist177 = new ArrayList(1);
        arraylist177.add("001");
        hashmap.put(Integer.valueOf(808), arraylist177);
        ArrayList arraylist178 = new ArrayList(1);
        arraylist178.add("KP");
        hashmap.put(Integer.valueOf(850), arraylist178);
        ArrayList arraylist179 = new ArrayList(1);
        arraylist179.add("HK");
        hashmap.put(Integer.valueOf(852), arraylist179);
        ArrayList arraylist180 = new ArrayList(1);
        arraylist180.add("MO");
        hashmap.put(Integer.valueOf(853), arraylist180);
        ArrayList arraylist181 = new ArrayList(1);
        arraylist181.add("KH");
        hashmap.put(Integer.valueOf(855), arraylist181);
        ArrayList arraylist182 = new ArrayList(1);
        arraylist182.add("LA");
        hashmap.put(Integer.valueOf(856), arraylist182);
        ArrayList arraylist183 = new ArrayList(1);
        arraylist183.add("001");
        hashmap.put(Integer.valueOf(870), arraylist183);
        ArrayList arraylist184 = new ArrayList(1);
        arraylist184.add("001");
        hashmap.put(Integer.valueOf(878), arraylist184);
        ArrayList arraylist185 = new ArrayList(1);
        arraylist185.add("BD");
        hashmap.put(Integer.valueOf(880), arraylist185);
        ArrayList arraylist186 = new ArrayList(1);
        arraylist186.add("001");
        hashmap.put(Integer.valueOf(881), arraylist186);
        ArrayList arraylist187 = new ArrayList(1);
        arraylist187.add("001");
        hashmap.put(Integer.valueOf(882), arraylist187);
        ArrayList arraylist188 = new ArrayList(1);
        arraylist188.add("001");
        hashmap.put(Integer.valueOf(883), arraylist188);
        ArrayList arraylist189 = new ArrayList(1);
        arraylist189.add("TW");
        hashmap.put(Integer.valueOf(886), arraylist189);
        ArrayList arraylist190 = new ArrayList(1);
        arraylist190.add("001");
        hashmap.put(Integer.valueOf(888), arraylist190);
        ArrayList arraylist191 = new ArrayList(1);
        arraylist191.add("MV");
        hashmap.put(Integer.valueOf(960), arraylist191);
        ArrayList arraylist192 = new ArrayList(1);
        arraylist192.add("LB");
        hashmap.put(Integer.valueOf(961), arraylist192);
        ArrayList arraylist193 = new ArrayList(1);
        arraylist193.add("JO");
        hashmap.put(Integer.valueOf(962), arraylist193);
        ArrayList arraylist194 = new ArrayList(1);
        arraylist194.add("SY");
        hashmap.put(Integer.valueOf(963), arraylist194);
        ArrayList arraylist195 = new ArrayList(1);
        arraylist195.add("IQ");
        hashmap.put(Integer.valueOf(964), arraylist195);
        ArrayList arraylist196 = new ArrayList(1);
        arraylist196.add("KW");
        hashmap.put(Integer.valueOf(965), arraylist196);
        ArrayList arraylist197 = new ArrayList(1);
        arraylist197.add("SA");
        hashmap.put(Integer.valueOf(966), arraylist197);
        ArrayList arraylist198 = new ArrayList(1);
        arraylist198.add("YE");
        hashmap.put(Integer.valueOf(967), arraylist198);
        ArrayList arraylist199 = new ArrayList(1);
        arraylist199.add("OM");
        hashmap.put(Integer.valueOf(968), arraylist199);
        ArrayList arraylist200 = new ArrayList(1);
        arraylist200.add("PS");
        hashmap.put(Integer.valueOf(970), arraylist200);
        ArrayList arraylist201 = new ArrayList(1);
        arraylist201.add("AE");
        hashmap.put(Integer.valueOf(971), arraylist201);
        ArrayList arraylist202 = new ArrayList(1);
        arraylist202.add("IL");
        hashmap.put(Integer.valueOf(972), arraylist202);
        ArrayList arraylist203 = new ArrayList(1);
        arraylist203.add("BH");
        hashmap.put(Integer.valueOf(973), arraylist203);
        ArrayList arraylist204 = new ArrayList(1);
        arraylist204.add("QA");
        hashmap.put(Integer.valueOf(974), arraylist204);
        ArrayList arraylist205 = new ArrayList(1);
        arraylist205.add("BT");
        hashmap.put(Integer.valueOf(975), arraylist205);
        ArrayList arraylist206 = new ArrayList(1);
        arraylist206.add("MN");
        hashmap.put(Integer.valueOf(976), arraylist206);
        ArrayList arraylist207 = new ArrayList(1);
        arraylist207.add("NP");
        hashmap.put(Integer.valueOf(977), arraylist207);
        ArrayList arraylist208 = new ArrayList(1);
        arraylist208.add("001");
        hashmap.put(Integer.valueOf(979), arraylist208);
        ArrayList arraylist209 = new ArrayList(1);
        arraylist209.add("TJ");
        hashmap.put(Integer.valueOf(992), arraylist209);
        ArrayList arraylist210 = new ArrayList(1);
        arraylist210.add("TM");
        hashmap.put(Integer.valueOf(993), arraylist210);
        ArrayList arraylist211 = new ArrayList(1);
        arraylist211.add("AZ");
        hashmap.put(Integer.valueOf(994), arraylist211);
        ArrayList arraylist212 = new ArrayList(1);
        arraylist212.add("GE");
        hashmap.put(Integer.valueOf(995), arraylist212);
        ArrayList arraylist213 = new ArrayList(1);
        arraylist213.add("KG");
        hashmap.put(Integer.valueOf(996), arraylist213);
        ArrayList arraylist214 = new ArrayList(1);
        arraylist214.add("UZ");
        hashmap.put(Integer.valueOf(998), arraylist214);
        return hashmap;
    }
}
